### ISSUE TITLE
Issues on latest macos and arm64. 

### ISSUE THREAD

**Issue by momomo** [gmethvin/directory-watcher#101]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/j/Library/Caches/JNA/temp/jna2952466869236905264.tmp: dlopen(/Users/j/Library/Caches/JNA/temp/jna2952466869236905264.tmp, 0x0001): tried: '/Users/j/Library/Caches/JNA/temp/jna2952466869236905264.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/j/Library/Caches/JNA/temp/jna2952466869236905264.tmp' (no such file), '/Users/j/Library/Caches/JNA/temp/jna2952466869236905264.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:19)
	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:128)
	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:61)
	
I've run it before on an Macbook pro max m2 .. but now on m3 max and latest macos and hitting a wall ...

**Comment by andersaaberg** [comment]
As a workaround, try to use the latest version of the dependency "net.java.dev.jna:jna", that worked for my Macbook M4 Max.

**Comment by gmethvin** [comment]
I updated the JNA dependency in version `0.19.0`.

**Comment by aaa-nine** [comment]
Many thanks for keeping the lib up-to-date.

I tried to update the directory-watcher version, but I kept getting a 4.x version of "net.java.dev.jna:jna" dependency and then I realized that it was downgraded by my older version of "org.grails:grails-console" - I fixed this by forcing 5.x. version of "net.java.dev.jna:jna". Sorry for the trouble, I will check the dependency tree more thorough next time.
